name: slash_task
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  sqflite: ^2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/1/
    - assets/images/2/
    - assets/images/3/
    - assets/images/4/
    - assets/images/5/
